#!/bin/bash
user_input=""
user_input2=""
user_input3=""
i=1

while [[ $user_input != "quit" ]]; do
  echo "Enter a command or 'quit' to exit"
  read -r user_input
  case $user_input in
  "poem")
    cat Zapovit
    ;;
  "letter")
    echo "What letter do you want to find?"
    read -r user_input2
    cat Zapovit | grep "$user_input2"
    ;;
  "lines")
    wc -l Zapovit
    ;;
  "lineswithletter")
    echo "Lines with what letter do you want to count?"
    read -r user_input3
    grep -c "$user_input3" Zapovit
    ;;
  "count")
    while [ $i -le 10 ]; do
      echo $i
      i=$((i + 1))
    done
    ;;
  "quit")
    echo "Goodbye!"
    ;;
  *)
    echo "Invalid command: '$user_input'"
    ;;
  esac
  done